# 华为云119.3.228.104:3307
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://119.3.228.104:3306/console?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=pei123

mybatis.type-aliases-package=com.ellison.springdemo.pojo

# redis
spring.redis.host=119.3.228.104
spring.redis.port=6379
spring.redis.password=
spring.redis.maxIdle=300
spring.redis.maxWait=1000
spring.redis.testOnBorrow=true
